"""Seed database with realistic SDG-aligned opportunities for demo."""
import asyncio
from datetime import datetime, timedelta
import random
from db.database import init_db, async_session
from db.models import Opportunity

SEED_OPPORTUNITIES = [
    {
        "title": "Sundara Solar Cooperative — Community-Owned Microgrids, Rural Kenya",
        "description": "A community energy cooperative providing affordable solar microgrids to 12,000 households across 40 villages in Western Kenya. Structured as a worker-owned cooperative with 30% community equity stake, enabling energy independence and local wealth retention. Partners with local NGOs for training and maintenance employment.",
        "source": "ImpactAlpha",
        "source_url": "https://impactalpha.com/sundara-solar-kenya",
        "organization": "Sundara Energy Cooperative",
        "country": "Kenya",
        "amount_usd": 2_500_000,
        "opportunity_type": "investment",
        "sector": "energy",
        "stage": "growth",
        "primary_sdgs": [7, 1, 8],
        "sdg_scores": {"1":7,"2":2,"3":3,"4":2,"5":3,"6":2,"7":10,"8":7,"9":5,"10":6,"11":4,"12":3,"13":5,"14":1,"15":3,"16":4,"17":6},
        "non_extractive_score": {"community_ownership": 9, "revenue_circularity": 8, "worker_equity": 9, "ecological_integrity": 7, "overall": 8.5},
        "impact_thesis": "Solar microgrids structured as community cooperatives directly advance SDG 7 (clean energy) while retaining economic value within rural communities. The cooperative structure ensures energy revenues fund local services rather than being extracted by outside investors.",
        "risk_flags": [],
        "tags": ["solar", "cooperative", "rural", "energy-access", "kenya"],
        "ai_confidence": 0.92,
        "status": "flagged",
        "is_featured": True,
    },
    {
        "title": "AgroRegenera Fund — Regenerative Agriculture Finance, Southeast Asia",
        "description": "A blended finance facility supporting 5,000 smallholder farmers transitioning to regenerative agriculture practices across Indonesia, Philippines, and Vietnam. The fund provides low-interest loans and technical assistance, with 20% of returns reinvested into local seed banks and farmer cooperatives.",
        "source": "Devex",
        "source_url": "https://devex.com/agroregenera-southeast-asia",
        "organization": "AgroRegenera Capital",
        "country": "Southeast Asia",
        "amount_usd": 15_000_000,
        "opportunity_type": "investment",
        "sector": "agriculture",
        "stage": "growth",
        "primary_sdgs": [2, 13, 15],
        "sdg_scores": {"1":5,"2":9,"3":4,"4":3,"5":4,"6":6,"7":2,"8":6,"9":4,"10":5,"11":2,"12":8,"13":8,"14":5,"15":9,"16":3,"17":7},
        "non_extractive_score": {"community_ownership": 7, "revenue_circularity": 8, "worker_equity": 6, "ecological_integrity": 9, "overall": 7.5},
        "impact_thesis": "Regenerative agriculture directly addresses SDG 2 (Zero Hunger) and SDG 15 (Life on Land) while building climate resilience for the world's most vulnerable food producers. The blended finance structure keeps returns modest but ensures capital recirculates into farmer capacity.",
        "risk_flags": ["Currency risk across three markets", "Slow adoption of regenerative practices"],
        "tags": ["regenerative-agriculture", "smallholder", "blended-finance", "climate-resilience"],
        "ai_confidence": 0.88,
        "status": "flagged",
        "is_featured": True,
    },
    {
        "title": "Salud Comunitaria — Community Health Clinic Network, Colombia & Peru",
        "description": "Expansion capital for a network of 28 community-managed primary health clinics serving indigenous and rural communities across Colombia and Peru. Clinics are governed by local health councils with indigenous representation on the board. Seeks $4M in concessional loans to build 12 new facilities.",
        "source": "NextBillion",
        "source_url": "https://nextbillion.net/salud-comunitaria",
        "organization": "Salud Comunitaria",
        "country": "Colombia, Peru",
        "amount_usd": 4_000_000,
        "opportunity_type": "investment",
        "sector": "health",
        "stage": "growth",
        "primary_sdgs": [3, 10, 16],
        "sdg_scores": {"1":6,"2":3,"3":10,"4":4,"5":7,"6":5,"7":2,"8":5,"9":3,"10":8,"11":6,"12":2,"13":2,"14":1,"15":2,"16":8,"17":5},
        "non_extractive_score": {"community_ownership": 9, "revenue_circularity": 8, "worker_equity": 7, "ecological_integrity": 5, "overall": 8.0},
        "impact_thesis": "Community-governed health clinics that return all surplus to facility improvement are a textbook non-extractive model. SDG 3 (Good Health) is advanced directly; indigenous governance structures strengthen SDG 16 (Peace, Justice, and Strong Institutions).",
        "risk_flags": [],
        "tags": ["health", "indigenous", "community-governance", "latin-america", "primary-care"],
        "ai_confidence": 0.94,
        "status": "flagged",
        "is_featured": False,
    },
    {
        "title": "GirlsCode Africa — Tech Skills & Income Fund, Sub-Saharan Africa",
        "description": "A grant-matching fund providing coding bootcamps, mentorship, and income-share agreements to 10,000 young women across Ghana, Nigeria, and Rwanda. Income-share structure caps repayment at 2x — repayments fund the next cohort of students.",
        "source": "SSIR",
        "source_url": "https://ssir.org/girlscode-africa",
        "organization": "GirlsCode Africa",
        "country": "Sub-Saharan Africa",
        "amount_usd": 3_200_000,
        "opportunity_type": "grant",
        "sector": "education",
        "stage": "early",
        "primary_sdgs": [4, 5, 8],
        "sdg_scores": {"1":5,"2":2,"3":4,"4":10,"5":10,"6":1,"7":2,"8":8,"9":6,"10":8,"11":3,"12":2,"13":2,"14":1,"15":1,"16":5,"17":6},
        "non_extractive_score": {"community_ownership": 6, "revenue_circularity": 9, "worker_equity": 8, "ecological_integrity": 3, "overall": 7.0},
        "impact_thesis": "The income-share agreement structure ensures that capital recirculates to fund the next generation — an explicit non-extractive design. SDG 4 and 5 are core focus; the model converts economic empowerment into structural change.",
        "risk_flags": ["ISA repayment rates uncertain in low-income contexts"],
        "tags": ["gender-equity", "education", "technology", "income-share", "africa"],
        "ai_confidence": 0.90,
        "status": "scored",
        "is_featured": False,
    },
    {
        "title": "Blue Carbon Fund — Mangrove Restoration & Community Livelihoods",
        "description": "A marine conservation fund financing mangrove restoration across 50,000 hectares in coastal Bangladesh, Myanmar, and the Philippines. Carbon credits are sold to corporates, with 60% of proceeds distributed to local fishing communities that monitor and protect the forests.",
        "source": "Alliance Magazine",
        "source_url": "https://alliancemagazine.org/blue-carbon-fund",
        "organization": "Blue Carbon Coalition",
        "country": "Bangladesh, Myanmar, Philippines",
        "amount_usd": 22_000_000,
        "opportunity_type": "investment",
        "sector": "climate",
        "stage": "growth",
        "primary_sdgs": [14, 13, 1],
        "sdg_scores": {"1":8,"2":4,"3":3,"4":2,"5":4,"6":5,"7":3,"8":6,"9":2,"10":7,"11":3,"12":5,"13":9,"14":10,"15":8,"16":4,"17":7},
        "non_extractive_score": {"community_ownership": 7, "revenue_circularity": 8, "worker_equity": 6, "ecological_integrity": 10, "overall": 7.8},
        "impact_thesis": "Mangrove restoration is one of the highest-leverage climate interventions available. Distributing 60% of carbon revenue to local communities creates genuine non-extractive carbon markets — communities become stewards rather than excluded bystanders.",
        "risk_flags": ["Carbon market volatility", "Verification of additionality needed"],
        "tags": ["blue-carbon", "mangrove", "carbon-credits", "marine", "community-revenue"],
        "ai_confidence": 0.87,
        "status": "scored",
        "is_featured": True,
    },
    {
        "title": "Cooperative Tech Hub — Worker-Owned Software Platform, Global South",
        "description": "Seed funding for a distributed software cooperative connecting 200 developer-owners across 14 countries in Africa and Southeast Asia. Members share equity, set their own rates, and collectively govern platform decisions. Targeting impact-aligned clients in education and health tech.",
        "source": "Pioneers Post",
        "source_url": "https://pioneerspost.com/cooperative-tech-hub",
        "organization": "Cooperative Tech Hub",
        "country": "Global South",
        "amount_usd": 800_000,
        "opportunity_type": "investment",
        "sector": "technology",
        "stage": "seed",
        "primary_sdgs": [8, 9, 10],
        "sdg_scores": {"1":4,"2":1,"3":3,"4":5,"5":6,"6":1,"7":2,"8":9,"9":9,"10":9,"11":3,"12":3,"13":2,"14":1,"15":1,"16":5,"17":8},
        "non_extractive_score": {"community_ownership": 10, "revenue_circularity": 9, "worker_equity": 10, "ecological_integrity": 4, "overall": 9.0},
        "impact_thesis": "Worker-owned technology cooperatives are the most direct expression of non-extractive finance — every line of surplus stays with the worker-owners. This model advances SDGs 8, 9, and 10 by building dignified, locally-controlled digital work.",
        "risk_flags": ["Governance complexity at scale"],
        "tags": ["cooperative", "tech", "worker-ownership", "global-south", "seed"],
        "ai_confidence": 0.91,
        "status": "flagged",
        "is_featured": True,
    },
    {
        "title": "WaterShed Trust — Indigenous Water Rights Fund, Amazon Basin",
        "description": "A legal defense and infrastructure fund protecting indigenous water rights across 12 Amazonian communities in Brazil and Peru. Finances water monitoring systems, legal representation, and community-led watershed governance structures.",
        "source": "ImpactAlpha",
        "source_url": "https://impactalpha.com/watershed-trust-amazon",
        "organization": "WaterShed Trust",
        "country": "Brazil, Peru",
        "amount_usd": 1_800_000,
        "opportunity_type": "grant",
        "sector": "climate",
        "stage": "early",
        "primary_sdgs": [6, 15, 16],
        "sdg_scores": {"1":5,"2":4,"3":5,"4":3,"5":5,"6":10,"7":1,"8":3,"9":2,"10":7,"11":3,"12":4,"13":6,"14":5,"15":9,"16":9,"17":6},
        "non_extractive_score": {"community_ownership": 10, "revenue_circularity": 7, "worker_equity": 5, "ecological_integrity": 10, "overall": 8.8},
        "impact_thesis": "Protecting indigenous water rights is fundamentally non-extractive — it reverses centuries of resource extraction from indigenous lands. SDGs 6 (Clean Water), 15 (Life on Land), and 16 (Peace and Justice) are inseparable in this context.",
        "risk_flags": ["Political risk in Brazil", "Legal timelines uncertain"],
        "tags": ["indigenous", "water-rights", "amazon", "legal-defense", "governance"],
        "ai_confidence": 0.89,
        "status": "scored",
        "is_featured": False,
    },
    {
        "title": "Urban Food Forest Network — Community Land Trust Model, US Cities",
        "description": "Replicating the Boston food forest model across 8 US cities through community land trusts. Permanently affordable land held in trust for urban agriculture, food security programming, and community gathering. Serving predominantly BIPOC neighborhoods with 0% displacement risk.",
        "source": "NextBillion",
        "source_url": "https://nextbillion.net/urban-food-forests",
        "organization": "Urban Food Forest Coalition",
        "country": "United States",
        "amount_usd": 5_500_000,
        "opportunity_type": "grant",
        "sector": "agriculture",
        "stage": "growth",
        "primary_sdgs": [2, 11, 10],
        "sdg_scores": {"1":6,"2":8,"3":6,"4":4,"5":6,"6":4,"7":2,"8":5,"9":3,"10":8,"11":9,"12":6,"13":4,"14":2,"15":7,"16":6,"17":5},
        "non_extractive_score": {"community_ownership": 10, "revenue_circularity": 9, "worker_equity": 7, "ecological_integrity": 8, "overall": 8.7},
        "impact_thesis": "Community land trusts permanently remove land from speculative markets — the original non-extractive land model. Urban food forests sitting on CLT land double-serve SDG 2 and SDG 11 while protecting low-income communities from displacement.",
        "risk_flags": [],
        "tags": ["community-land-trust", "food-security", "urban", "bipoc", "anti-displacement"],
        "ai_confidence": 0.93,
        "status": "flagged",
        "is_featured": False,
    },
    {
        "title": "Pacific Climate Bonds — Sovereign Resilience Finance, Pacific Islands",
        "description": "Sovereign blue bonds issued by Fiji, Vanuatu, and Tonga to finance coastal resilience infrastructure. Structured with IMF debt relief provisions so repayment can be suspended during climate disasters. Proceeds fund mangrove restoration, sea walls, and early warning systems.",
        "source": "Devex",
        "source_url": "https://devex.com/pacific-climate-bonds",
        "organization": "Pacific Resilience Finance Facility",
        "country": "Pacific Islands",
        "amount_usd": 85_000_000,
        "opportunity_type": "partnership",
        "sector": "climate",
        "stage": "mature",
        "primary_sdgs": [13, 11, 17],
        "sdg_scores": {"1":6,"2":3,"3":5,"4":2,"5":3,"6":4,"7":4,"8":4,"9":6,"10":5,"11":8,"12":4,"13":10,"14":7,"15":6,"16":6,"17":9},
        "non_extractive_score": {"community_ownership": 5, "revenue_circularity": 6, "worker_equity": 3, "ecological_integrity": 8, "overall": 5.5},
        "impact_thesis": "Climate-contingent debt relief is a genuine structural innovation — it prevents climate disasters from compounding sovereign debt crises. SDG 13 is the core focus, with SDG 17 (Partnerships) critical for the multilateral structure.",
        "risk_flags": ["Debt sustainability concerns", "Governance oversight needed"],
        "tags": ["sovereign-bonds", "climate-resilience", "pacific", "blue-bonds", "debt-relief"],
        "ai_confidence": 0.85,
        "status": "scored",
        "is_featured": False,
    },
    {
        "title": "Health Microfinance Network — Women's Preventive Care, South Asia",
        "description": "Micro-loans specifically for preventive healthcare expenses (mammograms, vaccines, dental) for women smallholder farmers in Bangladesh and Nepal. Disbursed through women's self-help groups that set their own repayment terms.",
        "source": "SSIR",
        "source_url": "https://ssir.org/health-microfinance-south-asia",
        "organization": "Samridhi Health Finance",
        "country": "Bangladesh, Nepal",
        "amount_usd": 1_200_000,
        "opportunity_type": "investment",
        "sector": "health",
        "stage": "early",
        "primary_sdgs": [3, 5, 1],
        "sdg_scores": {"1":8,"2":4,"3":10,"4":4,"5":9,"6":3,"7":1,"8":6,"9":3,"10":7,"11":2,"12":2,"13":1,"14":1,"15":1,"16":4,"17":5},
        "non_extractive_score": {"community_ownership": 8, "revenue_circularity": 7, "worker_equity": 6, "ecological_integrity": 3, "overall": 7.0},
        "impact_thesis": "Women-governed health self-help groups represent community ownership of financial infrastructure. Preventive care financing directly advances SDG 3 while the women's governance model advances SDG 5 structurally, not just symbolically.",
        "risk_flags": [],
        "tags": ["microfinance", "women", "preventive-care", "self-help-groups", "south-asia"],
        "ai_confidence": 0.91,
        "status": "scored",
        "is_featured": False,
    },
    {
        "title": "Reforestation Carbon + Agroforestry Credits, East Africa",
        "description": "Voluntary carbon project combining Afforestation/Reforestation credits with agroforestry payments across 80,000 hectares in Ethiopia, Uganda, and Tanzania. Smallholder farmers receive direct carbon payments quarterly, bypassing intermediaries.",
        "source": "World Bank",
        "source_url": "https://projects.worldbank.org/east-africa-reforestation",
        "organization": "World Bank / Green Climate Fund",
        "country": "East Africa",
        "amount_usd": 45_000_000,
        "opportunity_type": "partnership",
        "sector": "climate",
        "stage": "growth",
        "primary_sdgs": [13, 15, 2],
        "sdg_scores": {"1":7,"2":7,"3":3,"4":2,"5":4,"6":6,"7":2,"8":6,"9":3,"10":5,"11":2,"12":5,"13":10,"14":3,"15":10,"16":3,"17":8},
        "non_extractive_score": {"community_ownership": 7, "revenue_circularity": 8, "worker_equity": 6, "ecological_integrity": 10, "overall": 7.8},
        "impact_thesis": "Direct carbon payments to smallholder farmers eliminate the extractive intermediary layer typical of voluntary carbon markets. This model treats farmers as sovereign carbon stewards rather than labour inputs — advancing SDGs 13, 15, and 2 simultaneously.",
        "risk_flags": ["Carbon market price volatility"],
        "tags": ["reforestation", "carbon-credits", "agroforestry", "direct-payment", "east-africa"],
        "ai_confidence": 0.88,
        "status": "flagged",
        "is_featured": False,
    },
    {
        "title": "Circular Plastics Enterprise — Waste Picker Cooperative, Brazil",
        "description": "A plastics recycling enterprise owned 51% by waste picker cooperatives (catadores) in São Paulo and Rio. The cooperative stake ensures that recycling infrastructure investments benefit the communities who have long done this work informally.",
        "source": "Alliance Magazine",
        "source_url": "https://alliancemagazine.org/circular-plastics-brazil",
        "organization": "Catadores Cooperative Alliance",
        "country": "Brazil",
        "amount_usd": 3_700_000,
        "opportunity_type": "investment",
        "sector": "climate",
        "stage": "early",
        "primary_sdgs": [12, 8, 11],
        "sdg_scores": {"1":7,"2":2,"3":5,"4":3,"5":5,"6":4,"7":2,"8":9,"9":6,"10":8,"11":8,"12":9,"13":6,"14":5,"15":5,"16":4,"17":4},
        "non_extractive_score": {"community_ownership": 9, "revenue_circularity": 8, "worker_equity": 9, "ecological_integrity": 7, "overall": 8.5},
        "impact_thesis": "51% cooperative ownership of recycling infrastructure formalizes and rewards the informal labour that has long sustained urban material cycles. This model directly advances SDG 12 (Responsible Consumption) while building permanent worker equity.",
        "risk_flags": [],
        "tags": ["circular-economy", "waste-pickers", "cooperative", "plastics", "brazil"],
        "ai_confidence": 0.92,
        "status": "flagged",
        "is_featured": True,
    },
    {
        "title": "Digital Finance Inclusion — Unbanked Populations, West Africa",
        "description": "Mobile money platform with 1.3M users across Ghana, Côte d'Ivoire, and Burkina Faso. Seeking Series A to expand to Senegal and Mali. Platform charges 0.5% transaction fees — well below traditional banking — and holds reserves in local currencies.",
        "source": "ImpactAlpha",
        "source_url": "https://impactalpha.com/digital-finance-west-africa",
        "organization": "Kola Financial",
        "country": "West Africa",
        "amount_usd": 9_000_000,
        "opportunity_type": "investment",
        "sector": "finance",
        "stage": "early",
        "primary_sdgs": [10, 8, 1],
        "sdg_scores": {"1":8,"2":3,"3":3,"4":3,"5":7,"6":1,"7":1,"8":8,"9":7,"10":9,"11":4,"12":2,"13":1,"14":1,"15":1,"16":5,"17":6},
        "non_extractive_score": {"community_ownership": 4, "revenue_circularity": 6, "worker_equity": 5, "ecological_integrity": 3, "overall": 4.5},
        "impact_thesis": "Low-cost mobile finance for unbanked populations advances SDG 10 (Reduced Inequalities) by reducing the poverty penalty on financial transactions. However, the private-equity backed growth model limits non-extractive scores.",
        "risk_flags": ["VC-backed growth model limits community ownership", "Currency reserves need regulatory clarity"],
        "tags": ["mobile-money", "fintech", "financial-inclusion", "west-africa", "series-a"],
        "ai_confidence": 0.86,
        "status": "scored",
        "is_featured": False,
    },
    {
        "title": "Affordable Housing Land Trust — Indigenous Communities, Canada",
        "description": "Community land trust model delivering permanently affordable housing on indigenous-governed lands in British Columbia and Ontario. Federal CMHC funding sought for 300 units. Governance by indigenous housing societies ensures community control.",
        "source": "Devex",
        "source_url": "https://devex.com/indigenous-housing-canada",
        "organization": "Indigenous Housing Coalition Canada",
        "country": "Canada",
        "amount_usd": 28_000_000,
        "opportunity_type": "grant",
        "sector": "infrastructure",
        "stage": "growth",
        "primary_sdgs": [11, 10, 16],
        "sdg_scores": {"1":7,"2":2,"3":5,"4":3,"5":6,"6":4,"7":4,"8":5,"9":3,"10":9,"11":9,"12":4,"13":3,"14":1,"15":3,"16":8,"17":5},
        "non_extractive_score": {"community_ownership": 10, "revenue_circularity": 9, "worker_equity": 6, "ecological_integrity": 5, "overall": 8.5},
        "impact_thesis": "Indigenous land trusts are among the strongest non-extractive housing models available — permanently removing homes from speculative markets while rebuilding indigenous sovereignty. SDG 11 and 16 are jointly advanced.",
        "risk_flags": ["Federal funding timelines"],
        "tags": ["housing", "indigenous", "land-trust", "canada", "community-ownership"],
        "ai_confidence": 0.90,
        "status": "scored",
        "is_featured": False,
    },
    {
        "title": "OpenEd Platform — Open-Source Learning for Rural Schools, Global",
        "description": "Open-source learning management system designed for low-bandwidth, offline-first deployment in rural schools. Deployed in 2,400 schools across 18 countries. Seeking grant funding for teacher training programme and curriculum localisation.",
        "source": "NextBillion",
        "source_url": "https://nextbillion.net/opened-platform",
        "organization": "OpenEd Foundation",
        "country": "Global",
        "amount_usd": 2_100_000,
        "opportunity_type": "grant",
        "sector": "education",
        "stage": "growth",
        "primary_sdgs": [4, 9, 10],
        "sdg_scores": {"1":4,"2":1,"3":3,"4":10,"5":6,"6":1,"7":2,"8":4,"9":8,"10":7,"11":3,"12":3,"13":2,"14":1,"15":1,"16":5,"17":8},
        "non_extractive_score": {"community_ownership": 7, "revenue_circularity": 8, "worker_equity": 5, "ecological_integrity": 4, "overall": 7.0},
        "impact_thesis": "Open-source, offline-first educational software is non-extractive by design — no data harvesting, no platform lock-in, no recurring licence fees that drain school budgets. SDG 4 at scale.",
        "risk_flags": ["Sustainability without recurring revenue"],
        "tags": ["open-source", "edtech", "offline-first", "rural-education", "global"],
        "ai_confidence": 0.88,
        "status": "scored",
        "is_featured": False,
    },
    {
        "title": "Gender Lens Infrastructure Fund — Women-Led WASH Projects, Sub-Saharan Africa",
        "description": "Infrastructure fund financing water, sanitation, and hygiene projects that are majority-designed and managed by women. 40 projects across 8 countries. Returns blended with ODA to achieve below-market pricing for frontier markets.",
        "source": "SSIR",
        "source_url": "https://ssir.org/gender-lens-wash-fund",
        "organization": "Water Equity Fund",
        "country": "Sub-Saharan Africa",
        "amount_usd": 35_000_000,
        "opportunity_type": "investment",
        "sector": "infrastructure",
        "stage": "mature",
        "primary_sdgs": [6, 5, 3],
        "sdg_scores": {"1":6,"2":3,"3":8,"4":4,"5":9,"6":10,"7":2,"8":6,"9":4,"10":7,"11":5,"12":3,"13":3,"14":5,"15":3,"16":5,"17":7},
        "non_extractive_score": {"community_ownership": 7, "revenue_circularity": 7, "worker_equity": 7, "ecological_integrity": 6, "overall": 7.0},
        "impact_thesis": "Women-designed WASH systems have better maintenance outcomes and gender-appropriate design. The ODA blend reduces extraction of returns from frontier markets. SDG 6 + 5 as joint primary SDGs is a rare and powerful combination.",
        "risk_flags": [],
        "tags": ["wash", "gender-lens", "blended-finance", "oda", "women-led"],
        "ai_confidence": 0.91,
        "status": "flagged",
        "is_featured": False,
    },
    {
        "title": "Sovereign Seed Bank Fund — Agrobiodiversity, Andean Communities",
        "description": "Conservation and access fund for indigenous seed sovereignty across 300 Andean communities in Bolivia, Ecuador, and Peru. Communities retain IP ownership of all cultivars. Fund finances community-controlled seed banks, documentation, and legal protection.",
        "source": "ImpactAlpha",
        "source_url": "https://impactalpha.com/andean-seed-sovereignty",
        "organization": "Quechua Seed Sovereignty Network",
        "country": "Bolivia, Ecuador, Peru",
        "amount_usd": 1_500_000,
        "opportunity_type": "grant",
        "sector": "agriculture",
        "stage": "seed",
        "primary_sdgs": [2, 15, 16],
        "sdg_scores": {"1":5,"2":9,"3":3,"4":4,"5":5,"6":4,"7":1,"8":4,"9":3,"10":6,"11":3,"12":6,"13":5,"14":2,"15":8,"16":8,"17":5},
        "non_extractive_score": {"community_ownership": 10, "revenue_circularity": 8, "worker_equity": 7, "ecological_integrity": 9, "overall": 9.0},
        "impact_thesis": "Indigenous IP ownership of agrobiodiversity is the gold standard of non-extractive natural resource management. This fund directly counteracts centuries of biopiracy while securing food sovereignty (SDG 2) and biodiversity (SDG 15).",
        "risk_flags": ["Small scale limits", "Legal enforcement in multiple jurisdictions"],
        "tags": ["seed-sovereignty", "indigenous-ip", "biodiversity", "andean", "food-security"],
        "ai_confidence": 0.93,
        "status": "flagged",
        "is_featured": True,
    },
    {
        "title": "Climate Smart Fishing — Community Quotas, Pacific Islands",
        "description": "Grant facility supporting community-managed fisheries in Palau, FSM, and Solomon Islands. Communities hold tradeable fishing quotas and set sustainable harvest levels. Revenue from quota sales funds marine protected area enforcement.",
        "source": "World Bank",
        "source_url": "https://projects.worldbank.org/pacific-fisheries-community",
        "organization": "Pacific Community Fisheries Initiative",
        "country": "Pacific Islands",
        "amount_usd": 8_500_000,
        "opportunity_type": "grant",
        "sector": "climate",
        "stage": "early",
        "primary_sdgs": [14, 1, 10],
        "sdg_scores": {"1":7,"2":6,"3":4,"4":2,"5":4,"6":4,"7":2,"8":6,"9":3,"10":7,"11":3,"12":6,"13":5,"14":10,"15":7,"16":5,"17":6},
        "non_extractive_score": {"community_ownership": 8, "revenue_circularity": 8, "worker_equity": 7, "ecological_integrity": 9, "overall": 8.2},
        "impact_thesis": "Community-held fishing quotas transform coastal communities from resource-extraction targets into sovereign ocean stewards. SDG 14 (Life Below Water) is advanced through genuine governance, not top-down conservation.",
        "risk_flags": ["Quota trading market liquidity"],
        "tags": ["fisheries", "community-quotas", "marine", "pacific", "ocean-sovereignty"],
        "ai_confidence": 0.89,
        "status": "scored",
        "is_featured": False,
    },
    {
        "title": "Zero-Waste Cities Fund — Municipal Circular Economy, Southeast Europe",
        "description": "EU co-financed fund supporting zero-waste transitions in 6 municipalities in Serbia, North Macedonia, and Albania. Projects include municipal composting, repair cafes, and local material exchange programmes. Non-extractive structure: surplus returned to city budgets.",
        "source": "Devex",
        "source_url": "https://devex.com/zero-waste-cities-se-europe",
        "organization": "Zero Waste Europe / EBRD",
        "country": "Southeast Europe",
        "amount_usd": 12_000_000,
        "opportunity_type": "partnership",
        "sector": "infrastructure",
        "stage": "early",
        "primary_sdgs": [11, 12, 13],
        "sdg_scores": {"1":3,"2":3,"3":4,"4":3,"5":4,"6":5,"7":3,"8":5,"9":5,"10":5,"11":9,"12":9,"13":7,"14":4,"15":5,"16":5,"17":7},
        "non_extractive_score": {"community_ownership": 7, "revenue_circularity": 8, "worker_equity": 6, "ecological_integrity": 8, "overall": 7.5},
        "impact_thesis": "Municipal-level circular economy programmes with surplus returned to public budgets are inherently non-extractive. SDG 11 and 12 are tightly coupled here, with climate co-benefits through avoided landfill emissions.",
        "risk_flags": ["Municipal governance capacity"],
        "tags": ["circular-economy", "zero-waste", "municipal", "eastern-europe", "eu-funding"],
        "ai_confidence": 0.87,
        "status": "scored",
        "is_featured": False,
    },
    {
        "title": "Micro-Hydro Cooperative — Off-Grid Power, Nepal Highlands",
        "description": "Community-owned run-of-river micro-hydro installations in 22 remote villages in Humla and Dolpa districts. Each village cooperative owns its plant outright after a 5-year concessional loan period. Electricity powers both households and small enterprise.",
        "source": "Alliance Magazine",
        "source_url": "https://alliancemagazine.org/micro-hydro-nepal",
        "organization": "Nepal Cooperative Energy Initiative",
        "country": "Nepal",
        "amount_usd": 1_100_000,
        "opportunity_type": "investment",
        "sector": "energy",
        "stage": "growth",
        "primary_sdgs": [7, 1, 8],
        "sdg_scores": {"1":8,"2":3,"3":4,"4":3,"5":5,"6":5,"7":10,"8":7,"9":5,"10":6,"11":5,"12":3,"13":6,"14":1,"15":4,"16":4,"17":5},
        "non_extractive_score": {"community_ownership": 10, "revenue_circularity": 9, "worker_equity": 8, "ecological_integrity": 8, "overall": 9.0},
        "impact_thesis": "Run-of-river micro-hydro with community ownership after loan payoff is a classic patient capital / non-extractive model. Once the loan is repaid, 100% of the value stays in the village — pure SDG 7 impact with lasting structural change.",
        "risk_flags": ["Seismic and flood risk in mountain terrain"],
        "tags": ["micro-hydro", "cooperative", "rural-energy", "nepal", "off-grid"],
        "ai_confidence": 0.92,
        "status": "flagged",
        "is_featured": True,
    },
]


async def seed():
    await init_db()
    async with async_session() as session:
        from sqlalchemy import select, func
        from db.models import Opportunity
        count = (await session.execute(select(func.count()).select_from(Opportunity))).scalar()
        if count > 0:
            print(f"Database already has {count} opportunities — skipping seed.")
            return

        base_date = datetime(2025, 11, 1)
        for i, data in enumerate(SEED_OPPORTUNITIES):
            opp = Opportunity(
                title=data["title"],
                description=data["description"],
                source=data["source"],
                source_url=data["source_url"],
                published_at=base_date - timedelta(days=random.randint(0, 60)),
                scraped_at=base_date - timedelta(days=random.randint(0, 5)),
                scored_at=base_date - timedelta(days=random.randint(0, 3)),
                organization=data.get("organization"),
                country=data.get("country"),
                amount_usd=data.get("amount_usd"),
                opportunity_type=data["opportunity_type"],
                sector=data["sector"],
                stage=data["stage"],
                sdg_scores=data["sdg_scores"],
                primary_sdgs=data["primary_sdgs"],
                non_extractive_score=data["non_extractive_score"],
                impact_thesis=data["impact_thesis"],
                risk_flags=data["risk_flags"],
                tags=data["tags"],
                ai_confidence=data["ai_confidence"],
                status=data["status"],
                is_featured=data.get("is_featured", False),
            )
            session.add(opp)

        await session.commit()
        print(f"Seeded {len(SEED_OPPORTUNITIES)} opportunities.")


if __name__ == "__main__":
    asyncio.run(seed())
